### ISSUE TITLE
react-test-render fails to render draggable

### ISSUE THREAD

**Issue by arunasri** [atlassian/react-beautiful-dnd#1203]
## Bug or feature request?

Bug
## Get started
react-test-render throwing exception

## Duplicates

 Console

    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [Error: Invariant failed:
          provided.innerRef has not been provided with a HTMLElement.

          You can find a guide on using the innerRef callback functions at:
          https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md
        ]
          at reportException (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at invokeEventListeners (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
          at HTMLUnknownElementImpl._dispatch (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
          at invokeGuardedCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
          at commitRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5 Error: Invariant failed:
          provided.innerRef has not been provided with a HTMLElement.

          You can find a guide on using the innerRef callback functions at:
          https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

          at invariant (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
          at throwIfRefIsInvalid (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5855:74)
          at Droppable.componentDidMount (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5922:5)
          at commitLifeCycles (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9253:22)
          at commitAllLifeCycles (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10650:7)
          at HTMLUnknownElement.callCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2374:14)
          at invokeEventListeners (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
          at invokeGuardedCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
          at commitRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5
          at Object.unstable_runWithPriority (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:255:12)
          at completeRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12312:13)
          at performWorkOnRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12241:9)
          at performWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12149:7)
          at performSyncWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12123:3)
          at requestWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11992:5)
          at scheduleWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11807:5)
          at scheduleRootUpdate (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12406:3)
          at updateContainerAtExpirationTime (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12434:10)
          at updateContainer (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12445:10)
          at Object.create (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12878:5)
          at Suite.create (/Users/spasupuleti4/Downloads/reactivecjob/frontend/src/Pages/ConfigList/Table.test.js:43:6)
          at addSpecsToSuite (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/Env.js:339:25)
          at Env.describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/Env.js:308:7)
          at describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/jasmine_light.js:99:18)
          at Object.describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/src/Pages/ConfigList/Table.test.js:41:1)
          at Runtime._execModule (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runtime/build/index.js:694:13)
          at Runtime.requireModule (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runtime/build/index.js:376:14)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:129:13
          at Generator.next (<anonymous>)
          at step (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:170:30)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:189:14
          at new Promise (<anonymous>)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:167:12
          at jasmine2 (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:138:17)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:187:24
          at Generator.next (<anonymous>)
          at step (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:315:30)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:326:15
          at process._tickCallback (internal/process/next_tick.js:68:7)
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9036
      The above error occurred in the <Droppable> component:
          in Droppable (created by Connect(Droppable))
          in Connect(Droppable) (created by MaterialTable)
          in div (created by ScrollBar)
          in ScrollBar (created by MaterialTable)
          in div (created by Paper)
          in Paper (created by WithStyles(Paper))
          in WithStyles(Paper) (created by MaterialTable)
          in DragDropContext (created by MaterialTable)
          in MaterialTable (created by WithStyles(MaterialTable))
          in WithStyles(MaterialTable) (at Table.test.js:46)
          in Router (created by StaticRouter)
          in StaticRouter (at Table.test.js:45)
          in div (at Table.test.js:44)

      React will try to recreate this component tree from scratch using the error boundary you provided, DragDropContext.
    console.error node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5230
      %creact-beautiful-dnd

       %cAn error has occurred while a drag is occurring.
       Any existing drag will be cancelled.

       > Invariant failed:
       provided.innerRef has not been provided with a HTMLElement.

       You can find a guide on using the innerRef callback functions at:
       https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

       %c👷‍ This is a development only message. It will be removed in production builds. color: #00C584; font-size: 1.2em; font-weight: bold; line-height: 1.5 color: #723874;
    console.error node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5232
      raw Error: Invariant failed:
          provided.innerRef has not been provided with a HTMLElement.

          You can find a guide on using the innerRef callback functions at:
          https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

          at invariant (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
          at throwIfRefIsInvalid (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5855:74)
          at Droppable.componentDidMount (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5922:5)
          at commitLifeCycles (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9253:22)
          at commitAllLifeCycles (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10650:7)
          at HTMLUnknownElement.callCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2374:14)
          at invokeEventListeners (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
          at invokeGuardedCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
          at commitRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5
          at Object.unstable_runWithPriority (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:255:12)
          at completeRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12312:13)
          at performWorkOnRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12241:9)
          at performWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12149:7)
          at performSyncWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12123:3)
          at requestWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11992:5)
          at scheduleWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11807:5)
          at scheduleRootUpdate (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12406:3)
          at updateContainerAtExpirationTime (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12434:10)
          at updateContainer (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12445:10)
          at Object.create (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12878:5)
          at Suite.create (/Users/spasupuleti4/Downloads/reactivecjob/frontend/src/Pages/ConfigList/Table.test.js:43:6)
          at addSpecsToSuite (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/Env.js:339:25)
          at Env.describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/Env.js:308:7)
          at describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/jasmine_light.js:99:18)
          at Object.describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/src/Pages/ConfigList/Table.test.js:41:1)
          at Runtime._execModule (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runtime/build/index.js:694:13)
          at Runtime.requireModule (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runtime/build/index.js:376:14)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:129:13
          at Generator.next (<anonymous>)
          at step (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:170:30)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:189:14
          at new Promise (<anonymous>)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:167:12
          at jasmine2 (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:138:17)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:187:24
          at Generator.next (<anonymous>)
          at step (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:315:30)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:326:15
          at process._tickCallback (internal/process/next_tick.js:68:7)
    console.error node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5230
      %creact-beautiful-dnd

       %cAn error has occurred while a drag is occurring.
       Any existing drag will be cancelled.

       > Invariant failed:
       provided.innerRef has not been provided with a HTMLElement.

       You can find a guide on using the innerRef callback functions at:
       https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

       %c👷‍ This is a development only message. It will be removed in production builds. color: #00C584; font-size: 1.2em; font-weight: bold; line-height: 1.5 color: #723874;
    console.error node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5232
      raw ErrorEvent { isTrusted: [Getter] }
    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [Error: Invariant failed:
          provided.innerRef has not been provided with a HTMLElement.

          You can find a guide on using the innerRef callback functions at:
          https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md
        ]
          at reportException (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
          at invokeEventListeners (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
          at HTMLUnknownElementImpl._dispatch (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
          at invokeGuardedCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
          at commitRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5 Error: Invariant failed:
          provided.innerRef has not been provided with a HTMLElement.

          You can find a guide on using the innerRef callback functions at:
          https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

          at invariant (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
          at throwIfRefIsInvalid (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5855:74)
          at Droppable.componentDidMount (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:5922:5)
          at commitLifeCycles (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9253:22)
          at commitAllLifeCycles (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10650:7)
          at HTMLUnknownElement.callCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2374:14)
          at invokeEventListeners (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
          at HTMLUnknownElementImpl._dispatch (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
          at HTMLUnknownElementImpl.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
          at HTMLUnknownElement.dispatchEvent (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
          at Object.invokeGuardedCallbackDev (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2424:16)
          at invokeGuardedCallback (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2477:31)
          at commitRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10862:7)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12313:5
          at Object.unstable_runWithPriority (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/node_modules/scheduler/cjs/scheduler.development.js:255:12)
          at completeRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12312:13)
          at performWorkOnRoot (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12241:9)
          at performWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12149:7)
          at performSyncWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12123:3)
          at requestWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11992:5)
          at scheduleWork (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11807:5)
          at scheduleRootUpdate (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12406:3)
          at updateContainerAtExpirationTime (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12434:10)
          at updateContainer (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12445:10)
          at Object.create (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12878:5)
          at Suite.create (/Users/spasupuleti4/Downloads/reactivecjob/frontend/src/Pages/ConfigList/Table.test.js:43:6)
          at addSpecsToSuite (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/Env.js:339:25)
          at Env.describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/Env.js:308:7)
          at describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/jasmine/jasmine_light.js:99:18)
          at Object.describe (/Users/spasupuleti4/Downloads/reactivecjob/frontend/src/Pages/ConfigList/Table.test.js:41:1)
          at Runtime._execModule (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runtime/build/index.js:694:13)
          at Runtime.requireModule (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runtime/build/index.js:376:14)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:129:13
          at Generator.next (<anonymous>)
          at step (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:170:30)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:189:14
          at new Promise (<anonymous>)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:167:12
          at jasmine2 (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-jasmine2/build/index.js:138:17)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:187:24
          at Generator.next (<anonymous>)
          at step (/Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:315:30)
          at /Users/spasupuleti4/Downloads/reactivecjob/frontend/node_modules/jest-runner/build/run_test.js:326:15
          at process._tickCallback (internal/process/next_tick.js:68:7)
    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9036
      The above error occurred in the <Droppable> component:
          in Droppable (created by Connect(Droppable))
          in Connect(Droppable) (created by MaterialTable)
          in div (created by ScrollBar)
          in ScrollBar (created by MaterialTable)
          in div (created by Paper)
          in Paper (created by WithStyles(Paper))
          in WithStyles(Paper) (created by MaterialTable)
          in DragDropContext (created by MaterialTable)
          in MaterialTable (created by WithStyles(MaterialTable))
          in WithStyles(MaterialTable) (at Table.test.js:46)
          in Router (created by StaticRouter)
          in StaticRouter (at Table.test.js:45)
          in div (at Table.test.js:44)

**Comment by MikaelCarpenter** [comment]
I believe I'm seeing something similar when trying to mount with `enzyme@3.7.0` (`jest-enzyme@7.0.1`)

```console
TypeError: Right-hand side of 'instanceof' is not an object

      at isSvgElement (node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:6553:13)
      at throwIfSVG (node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:6559:5)
      at getDragHandleRef (node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:6564:5)
      at DragHandle.componentDidMount (node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js:7787:25)
```

Will update as I figure out more..

**Comment by alexreardon** [comment]
Are you setting up `innerRef` correctly? https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/using-inner-ref.md

Also, I suspect that this issue might go away with #1208 as we are running this check in a `useEffect`.

**Comment by alexreardon** [comment]
We are closing this issue due to inactivity. If you would like to continue the conversation feel free to reply to this issue and we can reopen it if needed.

**Comment by hawkeng** [comment]
Having the same issue, any updates on this?

**Comment by writercoder** [comment]
I was getting the error `provided.innerRef has not been provided with a HTMLElement.` when using storybook and storyshots. Everything worked in the browser.  Mounting directly with enzyme worked. 

It turns out you need to configure storyshots to use enzyme so my `storybook.test.js` now looks like this and everything works great.

```javascript
import initStoryshots from '@storybook/addon-storyshots';
import { mount } from 'enzyme';
import { createSerializer } from 'enzyme-to-json';

initStoryshots({
  renderer: mount,
  snapshotSerializers: [createSerializer({mode: 'deep'})],
});
```
