### ISSUE TITLE
Why i am seeing this ? 

### ISSUE THREAD

**Issue by pradhuman01** [atlassian/react-beautiful-dnd#2259]
Warning: Unsupported style property data-rbd-draggable-context-id. Did you mean dataRbdDraggableContextId?

Project Dependencies:-
"dependencies": {
    "@chakra-ui/react": "^1.4.1",
    "@emotion/css": "^11.1.3",
    "@emotion/react": "^11.1.5",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.1.5",
    "axios": "^0.21.1",
    "chart.js": "^3.3.2",
    "formik": "^2.2.6",
    "framer-motion": "^4.0.3",
    "next": "10.0.9",
    "next-auth": "^3.13.3",
    "react": "17.0.2",
    "react-beautiful-dnd": "^13.1.0",
    "react-chartjs-2": "^3.0.3",
    "react-dom": "17.0.2",
    "react-icons": "^4.2.0",
    "yup": "^0.32.9"
  }

**Comment by danieldelcore** [comment]
Hi there, can you provide some example code?

**Comment by pradhuman01** [comment]
> Hi there, can you provide some example code?

Actually i cant because its an product code.. Its against company rules..

**Comment by pradhuman01** [comment]
I am sharing error here..

`react_devtools_backend.js:2560 Warning: Unsupported style property data-rbd-draggable-context-id. Did you mean dataRbdDraggableContextId?
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at Draggable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:7883:65)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:231:75)
    at PrivateDraggable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8235:26)
    at PublicDraggable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8245:32)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at Droppable (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:8257:76)
    at ConnectFunction (webpack-internal:///./node_modules/react-redux/es/components/connectAdvanced.js:231:75)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at App (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:6854:25)
    at ErrorBoundary (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:117:35)
    at DragDropContext (webpack-internal:///./node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js:6983:19)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at eval (webpack-internal:///./node_modules/@chakra-ui/layout/dist/esm/flex.js:25:5)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:44:73)
    at Links (webpack-internal:///./pages/admin/[name]/links.js:44:77)
    at ColorModeProvider (webpack-internal:///./node_modules/@chakra-ui/color-mode/dist/esm/color-mode-provider.js:46:5)
    at ThemeProvider (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:78:71)
    at ThemeProvider (webpack-internal:///./node_modules/@chakra-ui/system/dist/esm/providers.js:20:5)
    at ChakraProvider (webpack-internal:///./node_modules/@chakra-ui/react/dist/esm/chakra-provider.js:21:5)
    at Provider (webpack-internal:///./node_modules/next-auth/dist/client/index.js:323:5)
    at MyApp (webpack-internal:///./pages/_app.js:29:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:152:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:641:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:772:24)`

**Comment by danieldelcore** [comment]
Are you able to reproduce this issue in a standalone repository or code sandbox?

**Comment by danieldelcore** [comment]
Will close this issue for now, feel free to reopen if this is still an issue for you.
